### ISSUE TITLE
Задача #6: Определение входных и выходных параметров

### ISSUE THREAD

**Issue by PQlavka** [PQlavka/stankin-SCRYAM#3]
Исходя из понимания о необходимых для создания функций библиотеки, определить входные и выходные параметры этих функций, их типы, содержание, основываясь на описании языка JavaScript
**Эпик**: #10 
**Время на выполнение**: 2 часа
**Время факт**: 1 часа

**Comment by WonderTruffle** [comment]
Входными данными для библиотеки является текстовый файл, содержащий информацию: 

- Тип объекта, анализ которого производится; 
- Название месяца; 
- Суммарный вклад за этот же промежуток времени (у.е.).

| Название объекта | Месяц | Сумма |
| ------------- | ------------- | ------------- |
| Объект 1 | Январь | 3000 |
| Объект 2 | Февраль | 2000 |
| ... | ... | ... |

- Выходными параметрами библиотеки является текстовый файл следующего содержания 
       * Название объекта.
       * Категория по ABC
       * Категория по XYZ

| Название объекта | ABC | XYZ |
| ------------- | ------------- | ------------- |
| Объект 1 | A | X |
| Объект 2 | C | Z |
| ... | ... | ... |
