### ISSUE TITLE
Задача #4: Определение требуемых модулей для библиотеки

### ISSUE THREAD

**Issue by PQlavka** [PQlavka/stankin-SCRYAM#4]
Исходя из документации (информации) об ABC/XYZ анализе - определить, какие модули нам необходимо описать в библиотеке
**Эпик**: #10 
**Время на выполнение**: 4 часа
**Время факт**: 4 часа

**Comment by WonderTruffle** [comment]
Библиотека ABC|XYZ анализа будет включать следующие модули
- Процедура импорта данных #14 
- Процедуры нахождения суммы, среднего, стандартного отклонения #15 
- Процедура Сортировки для выполнения ABC анализа #16 
- Процедура ABC анализа #17 
- Процедура XYZ анализа #18 
- Процедура совмещения результатов ABC и XYZ анализа (ABC+XYZ) #19 
- Процедура экспорта данных #24 
- Процедура группировки #25
