### ISSUE TITLE
Задача #3: Определить инструменты разработки

### ISSUE THREAD

**Issue by PQlavka** [PQlavka/stankin-SCRYAM#5]
**Эпик**: #10 
**Время на выполнение**: 2 часа
**Время факт**: 2 часа

**Comment by WonderTruffle** [comment]
- Разработка должна быть выполнена с использованием HTML, CSS, Javascript.
- При тестировании используется библиотека JQuery
- Сохранение наборов исходных данных и результатов должно обеспечиваться в локальной базе данных браузера пользователя.
